# Generated by Django 3.0.5 on 2020-04-29 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data',
            options={'verbose_name': 'DataTestingPostgres'},
        ),
    ]
