# Generated by Django 3.0.5 on 2020-04-29 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20200429_0132'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data',
            options={'verbose_name': 'Comment'},
        ),
    ]
